### ISSUE TITLE
View User Account Profile

### ISSUE THREAD

**Issue by NihlathakTheNecromancer** [BradWalsh97/SlightlyDelayedGram#10]
The user should be able to view posts from a user account in a dedicated page.

This includes:
- Page layout for a user account with public photos

This sub-task relates to #3

**Comment by nickydime** [comment]
For the user account, should we add any other features such as being able to message that user through viewing their profile?

**Comment by NihlathakTheNecromancer** [comment]
@nickydime  I will make another story for the messaging. I can break that one down into sub-tasks, one of which is to make messaging accessible from the user account page.

**Comment by NihlathakTheNecromancer** [comment]
@TheLilGrant This task is a duplication of task #11 . I think we should close this and mark it as "Won't Do"

**Comment by NihlathakTheNecromancer** [comment]
@TheLilGrant didn't realise this was already implemented, myabe just revise the task description to match what you developed.
