### ISSUE TITLE
Posting A Picture To The User Profile

### ISSUE THREAD

**Issue by johnab4444** [BradWalsh97/SlightlyDelayedGram#11]
The user should be able to upload a picture to the profile and post it.
This includes:

- Creating a form to upload a picture from device
- Integrating a picture feed into the user profile page showing the logged in user's pictures

Sub-task of issue #3

**Comment by NihlathakTheNecromancer** [comment]
I've completed posting a picture. Note that before committing I am reverting my changes to the database, this could be useful for keeping it clean for the reviewer. I've linked the pull request.

Let me know if you have any questions :)
