### ISSUE TITLE
Send an e-mail notification to followers

### ISSUE THREAD

**Issue by NihlathakTheNecromancer** [BradWalsh97/SlightlyDelayedGram#25]
This is a sub-task of the Story "Following a User" [#4 ]

To complete this sub-task:
- Send an e-mail notification to a user when they are followed by another user.

**Comment by johnab4444** [comment]
@NihlathakTheNecromancer Are you sure sending email notifications when a user posts a picture would be viable. If by chance you follow 1000 users, then receiving notifications from these users would get repetitive. Tell me what you think.

**Comment by NihlathakTheNecromancer** [comment]
@johnab4444 I agree, practically it is annoying. The alternative is an in-app notification stack. The e-mail implementation will quicker to accomplish, and we can use dummy e-mail accounts to demo it. Luckily we wouldn't have to simulate 1000 followers!
