### ISSUE TITLE
Setting up the development environment ( Points: 5 )

### ISSUE THREAD

**Issue by NihlathakTheNecromancer** [BradWalsh97/SlightlyDelayedGram#6]
This task will set-up the equivalent of a "Hello World" application with Django. Additionally, some set-up must be done in order to allow SemiDelayedGram to retrieve and store images remotely to a database. 

The database can be hosted using an AWS virtual machine using one of the following database servers compatible with Django:
- PostgreSQL
- MariaDB
- MySQL
- Oracle

Relevant Links:
- https://docs.djangoproject.com/en/3.0/topics/install/#database-installation

**Comment by BradWalsh97** [comment]
The environment is all set up. To publish the current version of the project, either master is cloned into the vm or it is copied to the VM using SCP. Then, once the server is launched it is publicly accessible by anyone.
